[build-system]
requires = ["setuptools>=45", "wheel", "setuptools_scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"

[project]
name = "mirror-dedupe"
dynamic = ["version"]
description = "Ubuntu mirror synchronisation with global deduplication"
readme = "README.md"
requires-python = ">=3.8"
license = {text = "MIT"}
authors = [
    {name = "Tim Hosking", email = "tim@mungerware.com"}
]
keywords = ["mirror", "deduplication", "hardlink", "ubuntu", "repository", "apt"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "Intended Audience :: System Administrators",
    "License :: OSI Approved :: MIT License",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: System :: Archiving :: Mirroring",
    "Topic :: System :: Systems Administration",
]
dependencies = [
    "PyYAML>=6.0",
]

[project.urls]
Homepage = "https://github.com/munger/mirror-dedupe"
"Bug Tracker" = "https://github.com/munger/mirror-dedupe/issues"
"Source Code" = "https://github.com/munger/mirror-dedupe"

[project.scripts]
mirror-dedupe = "mirror_dedupe.cli:main"

[tool.setuptools]
packages = ["mirror_dedupe"]

[tool.setuptools_scm]
